name: CI

on:
  push:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build and start project
        run: docker compose up --build -d

      - name: Wait for project
        run: sleep 20

      - name: Check backend
        run: curl -f http://localhost:8080/api/v1/tasks

      - name: Check frontend
        run: curl -f http://localhost:3000

      - name: Stop project
        if: always()
        run: docker compose down -v
